export const defaultAppSettings: AppSettings = {
  autoStart: false,
  closeWindowOption: "hide",
  fontFamily: "system-ui",
  borderRadius: 8,
  downloadPath: "",
  primaryColor: "#1ed760",
  backgroundColor: "",
  audioQuality: "auto",
  hiddenMenuKeys: [],
  displayMode: "list",
  ffmpegPath: "",
  themeMode: "system",
  pageTransition: "none",
  showSearchHistory: true,
  proxySettings: {
    type: "none",
    host: "",
    port: undefined,
    username: "",
    password: "",
  },
  sideMenuCollapsed: false,
  sideMenuWidth: 200,
  sideMenuCollectionFolded: {
    created: false,
    collected: false,
  },
  reportPlayHistory: true,
  localMusicDirs: [],
  desktopLyricsFontSize: 36,
  desktopLyricsColor: "#60a5fa",
  desktopLyricsFontFamily: "system-ui",
};
